[tox]
envlist = lint, mypy, py312, py313
toxworkdir = {env:TOX_WORK_DIR:.tox}

[testenv]
deps =
  -e .[dev]
setenv = HOME = {envtmpdir}
commands =
  pytest -v

[testenv:lint]
deps =
  ruff>=0.11,<1
commands =
  ruff check stage1_2gis tests/test_stage1_*.py

[gh-actions]
python =
    3.12: py312
    3.13: py313

[testenv:mypy]
deps =
  mypy>=1.10,<2
  types-requests>=2.27

commands =
  mypy {posargs}
